---

- name: "Create folder {{ workspace }}"
  file:
    path: "{{ workspace }}"
    recurse: yes
    state: directory
    owner: nginx
    group: nginx
    mode: 0775

- name: Clone {{ repo }} inside {{ workspace }}
  shell: git clone "{{ git_repo }}"
  args:
    chdir:  "{{ workspace }}"

- name: Copy repo content inside {{ workspace }}
  shell: cp -r $(basename {{ git_repo }})/* .
  args:
    chdir: "{{ workspace }}"

- name: "Change access right folder {{ workspace }}"
  file:
    path: "{{ workspace }}"
    recurse: yes
    state: directory
    owner: nginx
    group: nginx
    mode: 0775

- name: "Remove useless folder"
  shell: rm -r $(basename {{ git_repo }})
  args:
    chdir: "{{ workspace }}" 
    warn: False