---

- name: "Create folder {{ nginx_folder }}"
  file:
    path: "{{ nginx_folder }}"
    recurse: yes
    state: directory
    owner: {{ nginx_user }}
    group: {{ nginx_user }}
    mode: 0775

- name: Clone {{ repo }} inside {{ nginx_folder }}
  shell: git clone "{{ git_repo }}"
  args:
    chdir:  "{{ nginx_folder }}"

- name: Get workspace basename
  shell: basename {{ git_repo }}
  register: folder_name

- name: Copy repo content inside {{ nginx_folder }}
  shell: cp -r "{{ folder_name.stdout }}"/* .
  args:
    chdir: "{{ nginx_folder }}"

- name: "Change access right folder {{ nginx_folder }}"
  file:
    path: "{{ nginx_folder }}"
    recurse: yes
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0775

- name: "Remove useless folder"
  file:
    path: "{{ folder_name.stdout }}/*"
    recurse: yes
    state: absent